# encoding: utf8

# http://pypi.python.org/pypi/xlrd
import xlrd

TEMPLATE = """    "%(name)s":
    {
        "prefix": "%(prefix)s",
        "body":[
%(body)s
        ],
        "description": "%(description)s"
    },"""

BODY_TEMPLATE = "            \"%s\""

HEADER = """{
"##!---------------- Auto generated code: Generated by /data/Excel2Snippet.py ----------------##":{},
"## NOTE: Remove comma after last object if you re-Generated":{},
"""

FOOTER = "}"

book  = xlrd.open_workbook( 'KSP.xlsx' )
sheet = book.sheet_by_index( 0 )

rowLength = sheet.nrows

print( HEADER )
for row in range( 1, sheet.nrows ):
    name   = sheet.cell( row, 0 ).value.strip()
    prefix = sheet.cell( row, 1 ).value.strip()
    body   = sheet.cell( row, 3 ).value.strip()
    desc   = sheet.cell( row, 4 ).value.strip()

    if( len( prefix ) == 0 or len( body ) == 0 ):
        continue

    bodyArray    = body.split( "\n" )
    bodyArrayLen = len( bodyArray )
    tmp          = ""
    if( bodyArrayLen > 1 ):
        for i in range( bodyArrayLen ):
            tmp += BODY_TEMPLATE % ( bodyArray[ i ] )
            if( i + 1 < bodyArrayLen ):
                tmp += ",\n"
        body = tmp
    else:
        body = BODY_TEMPLATE % ( body )

    text = TEMPLATE % {
        "name":         name,
        "prefix":       prefix,
        "body":         body,
        "description":  desc,
    }
    print( text.encode( "utf-8" ) )

print( FOOTER )
