# encoding: utf-8

import re

# http://pypi.python.org/pypi/xlrd
import xlrd

import KspExcelUtil

TARGET  = "../src/features/generated/KSPCommandsCompletion.ts"

TEMPLATE = """
    "{intelliSense}":
    {{
        "snippet_string": "{snippet_string}",
        "signature":   "{signature}",
        "description": "{description}"
    }},"""

HEADER = """//
// Generated by /data/Excel2CompleteCommands.py
//
export var commands = {"""
FOOTER = "};"

def main():
    book       = xlrd.open_workbook( 'KSP_Completion.xlsx' )
    sheetNames = book.sheet_names()

    fw = open( TARGET, 'w' )

    fw.write( HEADER )

    sheet     = book.sheet_by_index( 0 )
    rowLength = sheet.nrows

    for row in range( 1, rowLength ):
        name    = KspExcelUtil.getCellFromColmnName( sheet, row, KspExcelUtil.HEADER_COMPLETE_NAME ).value.strip()
        snippet = KspExcelUtil.getCellFromColmnName( sheet, row, KspExcelUtil.HEADER_SNIPPET_BODY ).value.strip()
        sig     = KspExcelUtil.getCellFromColmnName( sheet, row, KspExcelUtil.HEADER_COMPLETE_SIG ).value.strip()
        desc    = KspExcelUtil.getCellFromColmnName( sheet, row, KspExcelUtil.HEADER_DESCRIPTION ).value.strip()

        desc = KspExcelUtil.append_newline( desc )
        snippet = KspExcelUtil.append_newline( snippet )

        if( len( name ) == 0 or re.match( r"^[^a-z|A-Z|_]", name ) != None ):
            continue

        desc = desc.replace( "\"", "\\\"" )
        sig  = sig.replace( "( ", "(" )
        sig  = sig.replace( " )", ")" )
        sig  = sig.replace( ", ", "," )

        text = TEMPLATE.format(
            intelliSense = name,
            snippet_string = snippet,
            signature    = sig,
            description  = desc
        )

        fw.write( text )

    fw.write( "\n" )
    fw.write( FOOTER )
    fw.write( "\n" )
    fw.close()
    print( "Done: " + TARGET )


if __name__ == "__main__":
    main()
