# encoding: utf8

# http://pypi.python.org/pypi/xlrd
import xlrd

import KspExcelUtil

TEMPLATE = """    "%(intelliSense)s":
    {
        "description": "%(description)s"
    },"""

BODY_TEMPLATE = "            \"%s\""

HEADER = """//
// Generated by /data/Excel2Complete.py
// NOTE: Remove comma after last object if you re-Generated.
exports.builtinVariables = {"""
FOOTER = "};"

book  = xlrd.open_workbook( 'KSP.xlsx' )
sheet = book.sheet_by_index( 0 )

rowLength = sheet.nrows

print( HEADER )
for row in range( 1, rowLength ):
    name   = KspExcelUtil.getCellFromColmnName( sheet, row, KspExcelUtil.HEADER_SNIPPET_NAME ).value.strip()
    desc   = KspExcelUtil.getCellFromColmnName( sheet, row, KspExcelUtil.HEADER_DESCRIPTION ).value.strip()

    if( len( name ) == 0 ):
        continue

    text = TEMPLATE % {
        "intelliSense": name,
        "description":  desc,
    }

    print( text.encode( "utf-8" ) )

print( FOOTER )
