# encoding: utf8

import re

# http://pypi.python.org/pypi/xlrd
import xlrd

import KspExcelUtil

TEMPLATE = """    "%(intelliSense)s":
    {
        "signature":   "%(signature)s",
        "description": "%(description)s"
    },"""

BODY_TEMPLATE = "            \"%s\""

HEADER = """//
// Generated by /data/Excel2CompleteCommands.py
// NOTE: Remove comma after last object if you re-Generated.
exports.commands = {"""
FOOTER = "};"

book  = xlrd.open_workbook( 'KSP.xlsx' )
sheet = book.sheet_by_index( 0 )

rowLength = sheet.nrows

print( HEADER )
for row in range( 1, rowLength ):
    name   = KspExcelUtil.getCellFromColmnName( sheet, row, KspExcelUtil.HEADER_COMPLETE_NAME ).value.strip()
    sig    = KspExcelUtil.getCellFromColmnName( sheet, row, KspExcelUtil.HEADER_COMPLETE_SIG ).value.strip()
    desc   = KspExcelUtil.getCellFromColmnName( sheet, row, KspExcelUtil.HEADER_DESCRIPTION ).value.strip()

    descArray = desc.split( "\n" )
    if( len( descArray ) > 1 ):
        tmp = ""
        for i in descArray:
            tmp += i + "\\n"
        desc = tmp

    if( len( name ) == 0 or re.match( r"^[^a-z|A-Z|_]", name ) != None ):
        continue

    desc = desc.replace( "\"", "\\\"" )
    sig  = sig.replace( "( ", "(" )
    sig  = sig.replace( " )", ")" )
    sig  = sig.replace( ", ", "," )

    text = TEMPLATE % {
        "intelliSense": name,
        "signature":    sig,
        "description":  desc,
    }

    print( text.encode( "utf-8" ) )

print( FOOTER )
