import os.path
import sys

# http://pypi.python.org/pypi/xlrd
import xlrd

import KspExcelUtil

def convert( input, output, sheet_name ):

    TEMPLATE = """
        "{intelliSense}":
        {{
            "snippet_string": "{snippet_string}",
            "signature":   "{signature}",
            "description": "{description}"
        }},"""

    HEADER = """//
    // Generated by /data/Excel2Completion.py
    //
    export var CompletionList = {"""
    FOOTER = "};"

    book    = xlrd.open_workbook( input )
    fw      = open( output, 'w' )

    fw.write( HEADER )

    sheet     = book.sheet_by_name( sheet_name )
    rowLength = sheet.nrows

    for row in range( 1, rowLength ):
        name    = KspExcelUtil.getCellFromColmnName( sheet, row, KspExcelUtil.HEADER_COMPLETE_NAME ).value.strip()
        snippet = KspExcelUtil.getCellFromColmnName( sheet, row, KspExcelUtil.HEADER_SNIPPET_BODY ).value.strip()
        sig     = KspExcelUtil.getCellFromColmnName( sheet, row, KspExcelUtil.HEADER_COMPLETE_SIG ).value.strip()
        desc    = KspExcelUtil.getCellFromColmnName( sheet, row, KspExcelUtil.HEADER_DESCRIPTION ).value.strip()

        desc = KspExcelUtil.append_newline( desc )
        snippet = KspExcelUtil.append_newline( snippet )

        if( len( name ) == 0 or name.startswith( "*" ) ):
            continue

        desc = desc.replace( "\"", "\\\"" )
        sig  = sig.replace( "( ", "(" )
        sig  = sig.replace( " )", ")" )
        sig  = sig.replace( ", ", "," )

        text = TEMPLATE.format(
            intelliSense = name,
            snippet_string = snippet,
            signature    = sig,
            description  = desc
        )

        fw.write( text )

    fw.write( "\n" )
    fw.write( FOOTER )
    fw.write( "\n" )
    fw.close()
    print( "Done: " + output )


if __name__ == "__main__":
    argv = sys.argv[1:]

    if( len(argv) < 2 ):
        print( "Usage: Excel2Completion.py <xlsx file> <output dir>" )
        sys.exit(1)

    xlsx_path  = argv[0]
    output_dir = argv[1]

    convert_list = [
        # 0: Input
        # 1: Target
        # 2: Sheet name
        [ xlsx_path, os.path.join( output_dir, "KSPCompletionCommand.ts" ),   "Command" ],
        [ xlsx_path, os.path.join( output_dir, "KSPCompletionVariable.ts" ),   "Variable" ],
    ]
    for i in convert_list:
        convert( i[0], i[1], i[2] )
