name: vsce-release

on:
  push:
    tags:
      - "v*"

jobs:
  #----------------------------------------------------------
  # Build VS Code Extension for Release
  #----------------------------------------------------------
  build-vsce-release:
    uses: ./.github/workflows/build_vscode_extension.yml
    secrets: inherit
    with:
      channel: release
      lsp-program-version: latest
      lsp-build-configuration: Release
      preview-flag: false
      pre-release-build: false
  #----------------------------------------------------------
  # Create GitHub Release
  #----------------------------------------------------------
  create-github-release:
    needs: build-vsce-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      #----------------------------------------------------------
      # Download VSIX artifact
      #----------------------------------------------------------
      - name: Download VSIX artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ needs.build-vsce-release.outputs.artifact-name }}
          path: dist

      #----------------------------------------------------------
      # Create GitHub Release (draft) and attach VSIX artifact
      #----------------------------------------------------------
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          gh release \
            create "${TAG_NAME}" \
            --draft \
            --repo "${{ github.repository }}" \
            --title "${TAG_NAME}" \
            --latest \
            --generate-notes \
            dist/*.vsix
